apiVersion: apps/v1
kind: Deployment
metadata:
  name: avengers-deploy
  labels:
    app: avengers-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avengers
  template:
    metadata:
      labels:
        app: avengers
    spec:
      containers:
      - name: iron-fist
        image: cupofjavatech/iron-fist:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: URL_RED_HOOD
            value: "http://localhost:8082/red-hood"
      - name: red-hood
        image: cupofjavatech/red-hood:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
          - name: URL_IRON_FIST
            value: "http://localhost:8081/iron-fist"
---
apiVersion: v1
kind: Service
metadata:
  name: iron-fist-service
spec:
  selector:
    app: avengers
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: red-hood-service
spec:
  selector:
    app: avengers
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
