version: "3.7"

services:

  iron-fist:
    image: "cupofjavatech/iron-fist:v1"
    container_name: iron-fist
    ports:
      - "8081:8081"
    environment:
      URL_RED_HOOD: http://red-hood:8082/red-hood
#      URL_RED_HOOD: http://localhost:8082/red-hood   -       doesn't work with container 
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
    external: true